- job:
    name: neutron-tempest-plugin-api
    parent: legacy-dsvm-base
    run: playbooks/neutron-tempest-plugin-api/run.yaml
    post-run: playbooks/neutron-tempest-plugin-api/post.yaml
    timeout: 10000
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-tempest-plugin
      - openstack/tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^releasenotes/.*$
      - ^doc/.*$
      - ^setup.cfg$

- job:
    name: neutron-tempest-plugin-scenario-linuxbridge
    parent: legacy-dsvm-base
    run: playbooks/neutron-tempest-plugin-scenario-linuxbridge/run.yaml
    post-run: playbooks/neutron-tempest-plugin-scenario-linuxbridge/post.yaml
    timeout: 10000
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-tempest-plugin
      - openstack/tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^releasenotes/.*$
      - ^doc/.*$
      - ^setup.cfg$
    voting: false

- job:
    name: neutron-tempest-plugin-dvr-multinode-scenario
    parent: legacy-dsvm-base-multinode
    run: playbooks/neutron-tempest-plugin-dvr-multinode-scenario/run.yaml
    post-run: playbooks/neutron-tempest-plugin-dvr-multinode-scenario/post.yaml
    nodeset: legacy-ubuntu-xenial-2-node
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-tempest-plugin
      - openstack/tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^releasenotes/.*$
      - ^doc/.*$
      - ^setup.cfg$
    voting: false

- project-template:
    name: neutron-tempest-plugin-jobs
    check:
      jobs:
        - neutron-tempest-plugin-api
        - neutron-tempest-plugin-dvr-multinode-scenario
        - neutron-tempest-plugin-scenario-linuxbridge
    gate:
      jobs:
        - neutron-tempest-plugin-api

- project:
    name: openstack/neutron-tempest-plugin
    templates:
      - neutron-tempest-plugin-jobs
